export interface YCCohort {
  id: string;
  label: string;
  companies: string[];
}

export const YC_COHORTS: YCCohort[] = [
  {
    id: "yc-s26",
    label: "YC S26",
    companies: [
      "Bujo (YC S26)", "Datost (YC S26)", "Arga Labs (YC S26)", "qomplement (YC S26)",
      "9 Mothers (YC S26)", "Indexable (YC S26)", "Minicor (YC S26)", "super{set} (YC S26)",
      "Playabl (YC S26)", "Manicule (YC S26)", "Asendia AI (YC S26)", "Runtime (YC S26)",
      "Arzana (YC S26)", "ProjectX (YC S26)", "OpenWork (YC S26)", "Amboras (YC S26)",
      "TesterArmy (YC S26)", "Foaster (YC S26)", "Harbor (YC S26)", "Adialante (YC S26)",
      "Keyframe Labs (YC S26)", "Oddpool (YC S26)", "Ontora (YC S26)", "Lamina Labs (YC S26)",
      "Kimpton (YC S26)", "Callab AI (YC S26)", "Standout (YC S26)", "Zolvo (YC S26)",
      "Kinro (YC S26)", "Hub.xyz (YC S26)", "Andustry (YC S26)", "Saffron (YC S26)",
      "Matforge (YC S26)", "Replicas (YC S26)", "ScienceSwarm (YC S26)", "Stage (YC S26)",
      "primitive (YC S26)", "Korso (YC S26)", "Dispatch (YC S26)", "Clara Health (YC S26)",
      "Prototyping.io (YC S26)", "Maquoketa Research (YC S26)", "Alchemy AI (YC S26)",
      "BenchSpan (YC S26)", "GojiberryAI (YC S26)", "Sazabi (YC S26)", "BioStack (YC S26)",
      "refortif.ai (YC S26)", "Totalis (YC S26)", "StableBrowse (YC S26)", "Interfaze (YC S26)",
      "InLoop (YC S26)", "Saudara.ai (YC S26)", "Complir (YC S26)", "Sherpa (YC S26)",
      "AICE Power (YC S26)", "Gigacatalyst (YC S26)", "Ara (YC S26)", "Lumius Imaging (YC S26)",
      "lab0 (YC S26)", "Userlens (YC S26)", "Tenet Industries (YC S26)", "Standard Signal (YC S26)",
      "Tasklet (YC S26)", "Salesgraph (YC S26)", "Pulsent (YC S26)", "Nine Fives (YC S26)",
      "Fuchsia (YC S26)", "Pentagon (YC S26)", "Klaimee (YC S26)", "Eden Robotics AI (YC S26)",
      "Dayjob (YC S26)", "Kuli (YC S26)", "smol machines (YC S26)", "Taiga (YC S26)",
      "Trellis (YC S26)", "Cignara (YC S26)", "Mount (YC S26)", "Sidekick (YC S26)",
      "Framewise Health (YC S26)", "Aster (YC S26)", "Ardent AI (YC S26)", "Silmaril (YC S26)",
      "Cohesion (YC S26)", "Elyra (YC S26)", "RegBase (YC S26)", "INTH (YC S26)",
      "InsForge (YC S26)", "Imperfect (YC S26)", "Smartbase (YC S26)", "Bloom (YC S26)",
      "Pairio (YC S26)", "Prism (YC S26)", "Kinect (YC S26)", "RentAHuman.ai (YC S26)",
      "Juno (YC S26)", "Huscarl (YC S26)", "Paper Star (YC S26)", "GovGuard (YC S26)",
      "Revnu (YC S26)", "Archer (YC S26)", "Drip (YC S26)", "memory.store (YC S26)",
      "Chert (YC S26)", "Ornadyne (YC S26)",
    ],
  },
  {
    id: "yc-w26",
    label: "YC W26",
    companies: [
      "Bidflow (YC W26)", "Galactic Resource Utilization Space, Inc. (GRU Space) (YC W26)",
      "Autumn AI (YC W26)", "Velum Labs (YC W26)", "Travo (YC W26)", "Oxus (YC W26)",
      "Voltair (YC W26)", "Inviscid AI (YC W26)", "Haladir (YC W26)", "Mantis Biotechnology (YC W26)",
      "CatchBack Cards (YC W26)", "FullSeam (YC W26)", "Corvera (YC W26)",
      "ARC Prize Foundation (YC W26)", "Valgo (YC W26)", "Hlabs (YC W26)", "Origin (YC W26)",
      "Panta (YC W26)", "Tensol (YC W26)", "Didit (YC W26)", "Kita (YC W26)", "Bits (YC W26)",
      "Ruma Care (YC W26)", "Lucent (YC W26)", "RunAnywhere (YC W26)", "Lance (YC W26)",
      "Sonarly (YC W26)", "Axis (YC W26)", "Lexius (YC W26)", "REV1 (YC W26)",
      "10x Science (YC W26)", "Sentrial (YC W26)", "LegalOS (YC W26)", "Protent (YC W26)",
      "BaseFrame (YC W26)", "Strand AI (YC W26)", "Beacon Health (YC W26)", "Burt (YC W26)",
      "ZeroSettle (YC W26)", "Kyten Technologies (YC W26)", "Avoice (YC W26)",
      "1code (21st.dev) (YC W26)", "Cumulus Labs (YC W26)", "Verdex (YC W26)",
      "AutoSitu (YC W26)", "MouseCat (YC W26)", "Skillsync (YC W26)", "RoboDock (YC W26)",
      "Luel (YC W26)", "CodeWisp (YC W26)", "OctaPulse (YC W26)", "Beyond Reach Labs (YC W26)",
      "DroneTector (YC W26)", "RamAIn (YC W26)", "Arcline (YC W26)", "Salus (YC W26)",
      "EigenPal (YC W26)", "Sparkles (YC W26)", "Ishiki Labs (YC W26)", "Perfectly (YC W26)",
      "Orthogonal (YC W26)", "Q2Q (YC W26)", "Opalite Health (YC W26)", "Compresr (YC W26)",
      "Unisson (YC W26)", "Stilta (YC W26)", "Laurence (YC W26)", "Hex Security (YC W26)",
      "Pax Historia (YC W26)", "Rhizome AI (YC W26)", "Prana (YC W26)", "Cardboard (YC W26)",
      "Jinba (YC W26)", "Seeing Systems (YC W26)", "Synthetic Sciences (YC W26)",
      "Visibl Semiconductors (YC W26)", "Patientdesk.ai (YC W26)", "Chamber (YC W26)",
      "Fenrock AI (YC W26)", "Maywood (YC W26)", "Traverse (YC W26)", "SideKit (YC W26)",
      "Ressl AI (YC W26)", "Robby (YC W26)", "sitefire (YC W26)",
    ],
  },
  {
    id: "yc-f25",
    label: "YC F25",
    companies: [
      "OpenBuilder (YC F25)", "Goldbridge (YC F25)", "Piggy Robotics (YC F25)",
      "Fifth Door (YC F25)", "Autonomous Technologies Group (YC F25)", "Prox (YC F25)",
      "Parametric (YC F25)", "Null Labs (YC F25)", "Nori (YC F25)", "Fernstone (YC F25)",
      "Mixy (YC F25)", "Digipals (YC F25)", "Efference (YC F25)", "Lapis (YC F25)",
      "Semiotic (YC F25)", "Remedy (YC F25)", "Brickanta (YC F25)", "AirCaps (YC F25)",
      "Uplane (YC F25)", "Structured AI (YC F25)", "Parse (YC F25)", "Brickwise (YC F25)",
      "Parrot (YC F25)", "MOVEdot (YC F25)", "Zavo (YC F25)", "Sylvian (YC F25)",
      "Nexus (YC F25)", "Bolna AI (YC F25)", "Hyperspell (YC F25)", "Scoop (YC F25)",
      "Aspect (YC F25)", "Deeptrace (YC F25)", "Locus (YC F25)", "Alt-X (YC F25)",
      "Caddy (YC F25)", "Sorce (YC F25)", "The Context Company (YC F25)", "Dari (YC F25)",
      "Lunavo (YC F25)", "Norra (YC F25)", "Kaigo Health (YC F25)", "Koyal (YC F25)",
      "PlayVision (YC F25)", "Iris (YC F25)", "Veria Labs (YC F25)", "Questom (YC F25)",
      "Cranston AI (YC F25)", "Hypercubic (YC F25)", "Nessie (YC F25)", "Wardstone (YC F25)",
      "AtlasGrid (YC F25)", "hillclimb (YC F25)", "Flick (YC F25)", "Semble AI (YC F25)",
      "Mod AI (YC F25)", "SellRaze (YC F25)", "Lakonia (YC F25)", "Nivara (YC F25)",
      "AnswerThis (YC F25)", "SF Tensor (YC F25)", "Unsiloed AI (YC F25)", "Allus AI (YC F25)",
      "Multifactor (YC F25)", "Sciloop (YC F25)", "LogosGuard (YC F25)", "Kestrel AI (YC F25)",
      "Tensr (YC F25)", "Agentic Fabriq (YC F25)", "Logical (YC F25)", "Aleph Lab (YC F25)",
      "Articulate (YC F25)", "Redapto (YC F25)", "Captain (YC F25)", "Sunflower (YC F25)",
      "Rovr (YC F25)", "Bravi (YC F25)", "ComplyDo (YC F25)", "Codyco (YC F25)",
      "Lexi (YC F25)", "Compyle (YC F25)", "Selfin (YC F25)", "Casey (YC F25)",
      "Play Health (YC F25)", "Thesis (YC F25)", "Inspector (YC F25)", "Cortex AI (YC F25)",
      "Pixley AI (YC F25)",
    ],
  },
  {
    id: "yc-su25",
    label: "YC Su25",
    companies: [
      "Stormy AI (YC Su25)", "Autumn (YC Su25)", "Fluidize (YC Su25)", "Ambral (YC Su25)",
      "Wayline (YC Su25)", "Serafis (YC Su25)", "Nixo (YC Su25)", "Cactus (YC Su25)",
      "Synthetic Society (YC Su25)", "Rid (YC Su25)", "Pingo AI (YC Su25)",
      "Adaptional (YC Su25)", "GETASAP (YC Su25)", "Meteor (YC Su25)", "Closera (YC Su25)",
      "Dedalus Labs (YC Su25)", "Acrely (YC Su25)", "The Prompting Company (YC Su25)",
      "MangoDesk (YC Su25)", "Halluminate (YC Su25)", "TraceRoot.AI (YC Su25)",
      "AgentMail (YC Su25)", "truthsystems (YC Su25)", "Blank Bio (YC Su25)",
      "Astor (YC Su25)", "Lanesurf (YC Su25)", "gitdot (YC Su25)", "Golpo (YC Su25)",
      "Shor (YC Su25)", "Pond (YC Su25)", "Liva AI (YC Su25)", "Playgent (YC Su25)",
      "Verne Robotics (YC Su25)", "ZeroEval (YC Su25)", "ContextFort (YC Su25)",
      "datafruit (YC Su25)", "Topological (YC Su25)", "Lark (YC Su25)", "bitrig (YC Su25)",
      "EffiGov (YC Su25)", "Design Arena (YC Su25)", "Lotas (YC Su25)", "Monarcha (YC Su25)",
      "Overdrive Health (YC Su25)", "Orange Slice (YC Su25)", "Nuntius (YC Su25)",
      "Wafer (YC Su25)", "Panels (YC Su25)", "Qualify.bot (YC Su25)", "Cyberdesk (YC Su25)",
      "Janet AI (YC Su25)", "Lilac (YC Su25)", "Imprezia (YC Su25)", "Alter (YC Su25)",
      "OnDeck AI (YC Su25)", "Skope (YC Su25)", "Frizzle (YC Su25)", "DeepGrove (YC Su25)",
      "Proliferate (YC Su25)", "Sagekit (YC Su25)", "Stockline (YC Su25)",
      "DeepAware AI (YC Su25)", "Tesora (YC Su25)", "Kestroll (YC Su25)", "Pangolin (YC Su25)",
      "CareSwift (YC Su25)", "Wedge (YC Su25)", "Slashy (YC Su25)", "cocreate (YC Su25)",
      "AgentHub (YC Su25)", "Nexa Labs (YC Su25)", "BootLoop (YC Su25)",
      "Stellon Labs (YC Su25)", "Kalinda (YC Su25)", "Parachute (YC Su25)",
      "Louiza Labs (YC Su25)", "Doe (YC Su25)", "IronLedger.ai (YC Su25)",
      "Interface (YC Su25)", "Trace (YC Su25)", "Fulcrum (YC Su25)", "b12 Labs (YC Su25)",
      "Flai (YC Su25)", "Embedder (YC Su25)", "Candytrail (YC Su25)", "Epicenter (YC Su25)",
      "Channel3 (YC Su25)", "GhostEye (YC Su25)", "Normal (YC Su25)", "Comena (YC Su25)",
      "VibeFlow (YC Su25)", "Nozomio (YC Su25)", "Mimos (YC Su25)",
    ],
  },
  {
    id: "yc-s25",
    label: "YC S25",
    companies: [
      "Leeroo (YC S25)", "Atum Works (YC S25)", "Willow (YC S25)", "Aviro (YC S25)",
      "Partcl (YC S25)", "Opine (YC S25)", "Atlog (YC S25)", "Blaxel (YC S25)",
      "QFEX (YC S25)", "Chestnut (YC S25)", "Frekil (YC S25)", "Plexe (YC S25)",
      "Kashikoi (YC S25)", "Aravolta (YC S25)", "Vybe (YC S25)", "nao Labs (YC S25)",
      "BitBoard (YC S25)", "Golf (YC S25)", "Notus Autonomous Systems (YC S25)",
      "cubic (YC S25)", "Bloom (YC S25)", "Avallon AI (YC S25)", "GroundControl (YC S25)",
      "Kanava AI (YC S25)", "Minerva (YC S25)", "Cua (YC S25)", "SynthioLabs (YC S25)",
      "Galen AI (YC S25)", "neoncoral (YC S25)", "Auctor (YC S25)", "Ralo (YC S25)",
      "Acolite (YC S25)", "Capacitive (YC S25)", "Claim Health (YC S25)", "Almond (YC S25)",
      "Chonkie (YC S25)", "HelixDB (YC S25)", "The Robot Learning Company (YC S25)",
      "Zeon Systems (YC S25)", "Dolphin (YC S25)", "Kaelio (YC S25)", "Beluga (YC S25)",
      "Clarm (YC S25)", "Sim (YC S25)", "stratify (YC S25)", "YouLearn (YC S25)",
      "TypeOS (YC S25)", "Percival (YC S25)", "Mbodi AI (YC S25)", "Kirana AI (YC S25)",
      "Caucus (YC S25)", "PgDog (YC S25)", "Attune (YC S25)", "Kestral (YC S25)",
      "Bluejay (YC S25)", "Better Auth (YC S25)", "Parsewise (YC S25)", "Refresh (YC S25)",
      "The LLM Data Company (YC S25)", "Tinfoil (YC S25)", "Trapeze (YC S25)",
      "Jeevy Fabrication (YC S25)", "Chiron (YC S25)", "VoiceOS (YC S25)",
      "Combinely (YC S25)", "Clado (YC S25)", "Tegore (YC S25)", "Sixtyfour (YC S25)",
      "Photonium (YC S25)", "Labric (YC S25)", "Opusense AI (YC S25)", "Clidey (YC S25)",
      "HABIT (YC S25)", "Kaizen (YC S25)", "Ticket Wallet (YC S25)", "RunRL (YC S25)",
      "Morphik (YC S25)", "Nomi (YC S25)", "Casco (YC S25)", "Crimson (YC S25)",
      "Flott HQ (YC S25)", "Lucis (YC S25)", "throxy (YC S25)", "Cleon (YC S25)",
      "Lyra (YC S25)", "Theta (YC S25)", "Novoflow (YC S25)", "Prism (YC S25)",
      "QualGent (YC S25)", "Human Behavior (YC S25)", "Alkali (YC S25)",
      "Besimple AI (YC S25)", "Jazzberry (YC S25)", "PowerMatrix (YC S25)",
      "Vesence (YC S25)",
    ],
  },
  {
    id: "yc-w25",
    label: "YC W25",
    companies: [
      "Egress Health (YC W25)", "Overstand Labs (YC W25)", "YouShift (YC W25)",
      "Uncommon Therapeutics (YC W25)", "Exin Therapeutics (YC W25)", "Delineate (YC W25)",
      "Onlook (YC W25)", "Invo (YC W25)", "Quantstruct (YC W25)", "Edexia (YC W25)",
      "Enhanced Radar (YC W25)", "Revise Robotics (YC W25)", "Trace (YC W25)",
      "Bild AI (YC W25)", "Candor (YC W25)", "Vetnio (YC W25)", "Leaping AI (YC W25)",
      "Flowtel (YC W25)", "Tweeks.io (YC W25)", "Excellence Learning (YC W25)",
      "Praxim (YC W25)", "Hey Telo (YC W25)", "SubImage (YC W25)", "Steinmetz (YC W25)",
      "Axiom (YC W25)", "Orchids (YC W25)", "Splash Inc. (YC W25)", "Stamp (YC W25)",
      "Alice.tech (YC W25)", "Dollyglot (YC W25)", "awen (YC W25)", "Karoo (YC W25)",
      "Dartboard Energy (YC W25)", "Astro (YC W25)", "Vocality Health (YC W25)",
      "Subtrace (YC W25)", "Scout (YC W25)", "Promptless (YC W25)", "Closure (YC W25)",
      "Conntour (YC W25)", "superglue (YC W25)", "Truffle AI (YC W25)", "Ovlo (YC W25)",
      "Contrario (YC W25)", "Sublingual (YC W25)", "Rocketable (YC W25)",
      "Toothy AI (YC W25)", "Verbiflow (YC W25)", "A1Base (YC W25)", "Altrina (YC W25)",
      "a0.dev (YC W25)", "Maritime Fusion (YC W25)", "Trava (YC W25)", "Tejas AI (YC W25)",
      "Caseflood.ai (YC W25)", "Weave (YC W25)", "Maive (YC W25)", "SalesPatriot (YC W25)",
      "Paragon (YC W25)", "careCycle (YC W25)", "Inversion Semiconductor (YC W25)",
      "Adam (YC W25)", "Rally (YC W25)", "Tergle (YC W25)", "Trim (YC W25)",
      "Amby Health (YC W25)", "Cardamon (YC W25)", "Bezel (YC W25)", "ZeroEntropy (YC W25)",
      "Oki (YC W25)", "Cifrato (YC W25)", "Mosaic (YC W25)", "Swerve (YC W25)",
      "Osmosis (YC W25)", "Operand (YC W25)", "HealthKey (YC W25)", "GradeWiz (YC W25)",
      "Mecha Health (YC W25)", "Cuckoo Labs (YC W25)", "finbar (YC W25)", "hud (YC W25)",
      "Olive (YC W25)", "PAX Markets (YC W25)", "Pave Robotics (YC W25)", "Gale (YC W25)",
      "Asteroid (YC W25)", "Macadamia (YC W25)", "Lucid (YC W25)", "Pickle (YC W25)",
      "Bindwell (YC W25)", "Stillwind (YC W25)", "Harbera (YC W25)", "Cenote (YC W25)",
      "Lopus AI (YC W25)",
    ],
  },
  {
    id: "yc-f24",
    label: "YC F24",
    companies: [
      "Variant (YC F24)", "Clarus (YC F24)", "Zeroframe (YC F24)", "Riveter AI (YC F24)",
      "Galini (YC F24)", "Avora (YC F24)", "telli (YC F24)", "Symphony (YC F24)",
      "Streamable (YC F24)", "Crouton (YC F24)", "Durate (YC F24)", "Gait (YC F24)",
      "Moonset Health (YC F24)", "Candle (YC F24)", "Getcho (YC F24)", "Darkgrade (YC F24)",
      "OpenFunnel (YC F24)", "HealthSpark (YC F24)", "Rulebase (YC F24)",
      "Afternoon.co (YC F24)", "Lightscreen AI (YC F24)", "Raycaster (YC F24)",
      "supercontrast (YC F24)", "Revyl (YC F24)", "VortexifyAI (YC F24)", "Vespper (YC F24)",
      "Sandra AI (YC F24)", "Archil (YC F24)", "Cekura (YC F24)", "Cosmic (YC F24)",
      "Matcha (YC F24)", "Reticular (YC F24)", "Smooth (YC F24)", "attimet (YC F24)",
      "ISSEN (YC F24)", "RevisionDojo (YC F24)", "CTGT (YC F24)", "RiskCube (YC F24)",
      "Keye (YC F24)", "Luthor (YC F24)", "Sphinx (YC F24)", "Lingo.dev (YC F24)",
      "Karmen (YC F24)", "Codebuff (YC F24)", "HYBRD (YC F24)", "Charm (YC F24)",
      "Unusual (YC F24)", "Platus (YC F24)", "Stewdio (YC F24)", "Pearson Labs (YC F24)",
      "vly.ai (YC F24)", "Tiny (YC F24)", "Crustdata (YC F24)", "AutoComputer (YC F24)",
      "Moonshine (YC F24)", "Dexter (YC F24)", "Curo (YC F24)", "Gecko Security (YC F24)",
      "PermitPortal (YC F24)", "Fresco (YC F24)", "Origami (YC F24)",
      "CollectWise (YC F24)", "Consus (YC F24)", "Capy (YC F24)", "Innate (YC F24)",
      "Gander (YC F24)", "Alex (YC F24)", "BrowserBook (YC F24)",
      "Diffusion Studio (YC F24)", "Metreecs (YC F24)", "Revi (YC F24)",
      "ArchiLabs (YC F24)", "Sunset (YC F24)", "Surge (YC F24)", "Edgedive (YC F24)",
      "FutureClinic (YC F24)", "Forerunner AI (YC F24)", "x1 (YC F24)", "Vaya (YC F24)",
      "Melder (YC F24)", "Ryvn (YC F24)", "SRE.ai (YC F24)", "Friday (YC F24)",
      "Relvy AI (YC F24)", "Ember (YC F24)", "Canvas (YC F24)", "Careforce (YC F24)",
      "Synth (YC F24)", "Roundabout Technologies (YC F24)", "Loombotic (YC F24)",
      "HumanLayer (YC F24)", "Apolink (YC F24)", "Asha Health (YC F24)",
    ],
  },
  {
    id: "yc-su24",
    label: "YC Su24",
    companies: [
      "Poka Labs (YC Su24)", "Simplex (YC Su24)", "Central (YC Su24)", "Fuse (YC Su24)",
      "Overeasy (YC Su24)", "ACX (YC Su24)", "Ligo Biosciences (YC Su24)", "Spur (YC Su24)",
      "Evolvere BioSciences (YC Su24)", "Coval (YC Su24)", "Ångström AI (YC Su24)",
      "Ultra (YC Su24)", "Abel Police (YC Su24)", "Roger (YC Su24)", "Miru (YC Su24)",
      "Spherecast (YC Su24)", "Apten (YC Su24)", "Domu Technology Inc. (YC Su24)",
      "Undermind (YC Su24)", "Superunit (YC Su24)", "Doublezero (YC Su24)",
      "Understood Care (YC Su24)", "Cheers (YC Su24)", "Mem0 (YC Su24)",
      "Glasskube (YC Su24)", "Saphira AI (YC Su24)", "Theseus (YC Su24)",
      "Synnax (YC Su24)", "Comfy Deploy (YC Su24)", "Spaceium Inc (YC Su24)",
      "Educato (YC Su24)", "ProhostAI (YC Su24)", "Pre (YC Su24)", "Hamming AI (YC Su24)",
      "mdhub (YC Su24)", "ClaimSorted (YC Su24)", "Entangl (YC Su24)",
      "Codes Health (YC Su24)", "Unsloth AI (YC Su24)", "Random Labs (YC Su24)",
      "DigitalCarbon (YC Su24)", "Bayesline (YC Su24)", "Flyflow (YC Su24)",
      "Callback (YC Su24)", "Tabula (YC Su24)", "Invaria (YC Su24)",
      "Stack Auth (YC Su24)", "Sage (YC Su24)", "VideoGen (YC Su24)", "Phonely (YC Su24)",
      "Corgi Insurance (YC Su24)", "Maitai (YC Su24)", "Wordware (YC Su24)",
      "Sorcerer (YC Su24)", "FirstWork (YC Su24)", "ideate.xyz (YC Su24)",
      "Stardrift (YC Su24)", "Decisional AI (YC Su24)",
      "Azalea Robotics Corporation (YC Su24)", "RetroFix (YC Su24)", "Unbound (YC Su24)",
      "Hyrex (YC Su24)", "Silurian (YC Su24)", "NetworkOcean (YC Su24)",
      "Cloudglue (YC Su24)", "Rewbi (YC Su24)", "Proxis (YC Su24)", "Zuni (YC Su24)",
      "Scape (YC Su24)", "DeepSim, Inc. (YC Su24)", "Storia AI (YC Su24)",
      "Offstream (YC Su24)", "Elevate (YC Su24)", "Lucible (YC Su24)", "Dodo (YC Su24)",
      "Ares Industries (YC Su24)", "RunLocal AI (YC Su24)", "CodeViz (YC Su24)",
      "Parahelp (YC Su24)", "Lore (YC Su24)", "Snowpilot (YC Su24)", "MinusX (YC Su24)",
      "camfer (YC Su24)", "Tivara (YC Su24)", "Kenley (YC Su24)", "Tandem (YC Su24)",
      "Weave Robotics (YC Su24)", "Gauge (YC Su24)", "AminoAnalytica (YC Su24)",
      "Dench.com (YC Su24)",
    ],
  },
  {
    id: "yc-w24",
    label: "YC W24",
    companies: [
      "GovernGPT (YC W24)", "Yenmo (YC W24)", "jo (YC W24)", "Onyx (YC W24)",
      "Lantern (YC W24)", "Driver (YC W24)", "Gumloop (YC W24)",
      "Event Horizon Labs (YC W24)", "Upsolve AI (YC W24)", "Navier AI (YC W24)",
      "DryMerge (YC W24)", "Relari (YC W24)", "Tesseral (YC W24)", "RadMate AI (YC W24)",
      "Scritch (YC W24)", "Legora (formerly Leya) (YC W24)", "ego (YC W24)",
      "Stitch Technologies (YC W24)", "PurplePages (YC W24)", "Greptile (YC W24)",
      "Ubicloud (YC W24)", "Happenstance (YC W24)", "Duckie (YC W24)",
      "ion design (YC W24)", "Maihem (YC W24)", "Sonia (YC W24)", "Kabilah (YC W24)",
      "Tracecat (YC W24)", "Precip (YC W24)", "Nuanced (YC W24)", "Maia (YC W24)",
      "Andon Labs (YC W24)", "Reducto (YC W24)", "Momentic (YC W24)",
      "Tuesday Lab (YC W24)", "Tile (YC W24)", "Newton (YC W24)", "Quary (YC W24)",
      "malibou (YC W24)", "Alex (YC W24)", "Lumen Payments (YC W24)",
      "nCompass Technologies (YC W24)", "Argon AI, Inc. (YC W24)", "Mango Health (YC W24)",
      "Garage (YC W24)", "Buster (YC W24)", "DGI Apparel (YC W24)", "Aidy (YC W24)",
      "Pivot Robotics (YC W24)", "Fractal Labs (YC W24)", "Agentic Labs (YC W24)",
      "Carousel Technologies (YC W24)", "Basalt (YC W24)", "Leaping (YC W24)",
      "MathDash (YC W24)", "Assembly (YC W24)", "Avery (YC W24)", "Patchwork (YC W24)",
      "PointOne (YC W24)", "Paradigm (YC W24)", "Arini (YC W24)", "FurtherAI (YC W24)",
      "ROE (YC W24)", "SuretyNow (YC W24)", "Octolane AI (YC W24)", "Artisan (YC W24)",
      "Eggnog (YC W24)", "Greenboard (YC W24)", "Ecliptor (YC W24)",
      "Trellis AI (YC W24)", "Topo (YC W24)", "Verse Therapy (YC W24)",
      "TokenOwl (YC W24)", "Yoneda Labs (YC W24)", "SynsoryBio (YC W24)",
      "Copper Health (YC W24)", "Blume Benefits (YC W24)", "atopile (YC W24)",
      "PartnerHQ (YC W24)", "Tusk (YC W24)", "Engines (YC W24)", "OneGrep (YC W24)",
      "Selera Medical (YC W24)", "Lucite (YC W24)", "Attunement (YC W24)",
      "CloudCruise (YC W24)", "StarJar (YC W24)", "Meticulate (YC W24)",
      "Celest (YC W24)", "Glimmer (YC W24)", "Zaymo (YC W24)", "PromptArmor (YC W24)",
    ],
  },
];
